/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  add_alias: {
    denom: string;
    token: string;
  };
} | {
  change_owner: {
    new_owner: Addr;
  };
} | {
  grant_role: {
    addr: Addr;
    role: string;
  };
} | {
  revoke_role: {
    addr: Addr;
    role: string;
  };
} | {
  pause: {
    expires_at: number;
  };
} | {
  release: {};
};
export type Addr = string;
export type QueryMsg = {
  get_config: {};
} | {
  convert: {
    token: string;
  };
};
export interface ConvertResponse {
  alias: string;
  token: string;
}
export interface ConfigResponse {
  owner: Addr;
}