/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Denommanager.types";
import * as _1 from "./Denommanager.client";
import * as _2 from "./Gateway.types";
import * as _3 from "./Gateway.client";
import * as _4 from "./Liquiditymanager.types";
import * as _5 from "./Liquiditymanager.client";
export namespace contracts {
  export const Denommanager = { ..._0,
    ..._1
  };
  export const Gateway = { ..._2,
    ..._3
  };
  export const Liquiditymanager = { ..._4,
    ..._5
  };
}