/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./Denommanager.client";
import * as _3 from "./Gateway.client";
import * as _5 from "./Liquiditymanager.client";
export declare namespace contracts {
    const Denommanager: {
        DenommanagerQueryClient: typeof _1.DenommanagerQueryClient;
        DenommanagerClient: typeof _1.DenommanagerClient;
    };
    const Gateway: {
        GatewayQueryClient: typeof _3.GatewayQueryClient;
        GatewayClient: typeof _3.GatewayClient;
    };
    const Liquiditymanager: {
        LiquiditymanagerQueryClient: typeof _5.LiquiditymanagerQueryClient;
        LiquiditymanagerClient: typeof _5.LiquiditymanagerClient;
    };
}
//# sourceMappingURL=index.d.ts.map