/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export interface InstantiateMsg {
    denom: string;
    lp_denom: string;
    unbonding_period: number;
}
export declare type ExecuteMsg = {
    deposit: {
        depositor?: Addr | null;
    };
} | {
    withdraw: {
        amount: Coin;
        withdrawer?: Addr | null;
    };
} | {
    delegate: {};
} | {
    undelegate: {};
} | {
    bond: {};
} | {
    start_unbond: {
        amount: Uint128;
    };
} | {
    unbond: {
        unbond_id: number;
    };
} | {
    change_owner: {
        new_owner: Addr;
    };
} | {
    grant_role: {
        addr: Addr;
        role: string;
    };
} | {
    revoke_role: {
        addr: Addr;
        role: string;
    };
} | {
    pause: {
        expires_at: number;
    };
} | {
    release: {};
} | {
    change_config: {
        unbonding_period: number;
    };
};
export declare type Addr = string;
export declare type Uint128 = string;
export interface Coin {
    amount: Uint128;
    denom: string;
    [k: string]: unknown;
}
export declare type QueryMsg = {
    get_config: {};
} | {
    pause_info: {};
} | {
    get_balance: {
        depositor: Addr;
    };
} | {
    get_bond: {
        bonder: Addr;
    };
} | {
    get_unbond: {
        unbond_id: number;
    };
} | {
    get_unbonds_by_owner: {
        owner: Addr;
    };
};
export interface GetBalanceResponse {
    assets: Coin[];
    depositor: Addr;
}
export interface GetBondResponse {
    amount: Uint128;
    bond_time: number;
}
export interface ConfigResponse {
    denom: string;
    lp_denom: string;
    owner: Addr;
    unbonding_period: number;
}
export interface GetUnbondResponse {
    amount: Uint128;
    owner: Addr;
    unbond_id: number;
    unbond_time: number;
}
export interface GetUnbondListResponse {
    items: GetUnbondResponse[];
}
export interface PauseInfoResponse {
    expires_at?: number | null;
    paused: boolean;
}
//# sourceMappingURL=Liquiditymanager.types.d.ts.map