name: format

on: push

jobs:
  check:
    strategy:
      fail-fast: true

    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml')}}
  
      - uses: actions-rs/cargo@v1
        with:
          command: clippy