name: test

on: pull_request

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          path: ~/target
          key: ${{ runner.os }}-rust-${{ hashFiles('Cargo.toml')}}

      - name: Run Test
        run: cargo test --workspace
